namespace ERP.Infrastructure.Migrations;

public static class MigrationCatalog
{
    private const string TableOptions = "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";

    public static IReadOnlyList<MigrationDefinition> All { get; } =
    [
        new("202608270001_create_system_metadata.js",
        [
            $"""CREATE TABLE `system_metadata` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, `metadata_key` VARCHAR(100) NOT NULL, `metadata_value` VARCHAR(255) NOT NULL, `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY `system_metadata_metadata_key_unique` (`metadata_key`)) {TableOptions}""",
            "INSERT INTO `system_metadata` (`metadata_key`, `metadata_value`) VALUES ('schema_foundation', '1.1')"
        ], ["DROP TABLE `system_metadata`"]),

        new("202608270002_create_plans.js",
        [
            $"""CREATE TABLE `plans` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `code` VARCHAR(50) NOT NULL, `name` VARCHAR(120) NOT NULL, `description` TEXT NULL, `is_active` TINYINT(1) NOT NULL DEFAULT 1, `is_public` TINYINT(1) NOT NULL DEFAULT 0, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY `uq_plans_code` (`code`)) {TableOptions}""",
            $"""CREATE TABLE `plan_limits` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `plan_id` VARCHAR(36) NOT NULL, `key` VARCHAR(80) NOT NULL, `value` BIGINT UNSIGNED NOT NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT `fk_plan_limits_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_plan_limits_plan_key` (`plan_id`,`key`), KEY `idx_plan_limits_key` (`key`)) {TableOptions}"""
        ], ["DROP TABLE `plan_limits`", "DROP TABLE `plans`"]),

        new("202608270003_create_tenant_organization.js",
        [
            $"""CREATE TABLE `tenants` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `name` VARCHAR(160) NOT NULL, `slug` VARCHAR(100) NOT NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'active', `timezone` VARCHAR(64) NOT NULL DEFAULT 'America/Sao_Paulo', `locale` VARCHAR(10) NOT NULL DEFAULT 'pt-BR', `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY `uq_tenants_slug` (`slug`), KEY `idx_tenants_status` (`status`), CONSTRAINT `chk_tenants_status` CHECK (`status` IN ('active','suspended','cancelled'))) {TableOptions}""",
            $"""CREATE TABLE `companies` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `tenant_id` VARCHAR(36) NOT NULL, `legal_name` VARCHAR(180) NOT NULL, `trade_name` VARCHAR(180) NULL, `tax_id_root` VARCHAR(8) NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'active', `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT `fk_companies_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_companies_tenant_id` (`tenant_id`,`id`), KEY `idx_companies_tenant_status` (`tenant_id`,`status`), KEY `idx_companies_tenant_tax_root` (`tenant_id`,`tax_id_root`), CONSTRAINT `chk_companies_status` CHECK (`status` IN ('active','inactive')), CONSTRAINT `chk_companies_tax_id_root` CHECK (`tax_id_root` IS NULL OR LENGTH(`tax_id_root`) = 8 AND `tax_id_root` NOT REGEXP '[^0-9]')) {TableOptions}""",
            $"""CREATE TABLE `branches` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `tenant_id` VARCHAR(36) NOT NULL, `company_id` VARCHAR(36) NOT NULL, `code` VARCHAR(50) NOT NULL, `legal_name` VARCHAR(180) NOT NULL, `trade_name` VARCHAR(180) NULL, `tax_id` VARCHAR(14) NULL, `is_headquarters` TINYINT(1) NOT NULL DEFAULT 0, `status` VARCHAR(20) NOT NULL DEFAULT 'active', `email` VARCHAR(254) NULL, `phone` VARCHAR(20) NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `headquarters_company_id` CHAR(36) GENERATED ALWAYS AS (CASE WHEN `is_headquarters` = 1 THEN `company_id` ELSE NULL END) STORED, CONSTRAINT `fk_branches_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_branches_tenant_company` FOREIGN KEY (`tenant_id`,`company_id`) REFERENCES `companies` (`tenant_id`,`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_branches_tenant_id` (`tenant_id`,`id`), UNIQUE KEY `uq_branches_company_code` (`company_id`,`code`), UNIQUE KEY `uq_branches_tenant_tax_id` (`tenant_id`,`tax_id`), UNIQUE KEY `uq_branches_one_headquarters` (`company_id`,`headquarters_company_id`), KEY `idx_branches_tenant_status` (`tenant_id`,`status`), KEY `idx_branches_company` (`company_id`), KEY `idx_branches_tax_id` (`tax_id`), CONSTRAINT `chk_branches_status` CHECK (`status` IN ('active','inactive')), CONSTRAINT `chk_branches_tax_id` CHECK (`tax_id` IS NULL OR LENGTH(`tax_id`) = 14 AND `tax_id` NOT REGEXP '[^0-9]')) {TableOptions}""",
            $"""CREATE TABLE `branch_addresses` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `tenant_id` VARCHAR(36) NOT NULL, `branch_id` VARCHAR(36) NOT NULL, `postal_code` VARCHAR(8) NULL, `street` VARCHAR(180) NOT NULL, `number` VARCHAR(30) NOT NULL, `complement` VARCHAR(120) NULL, `district` VARCHAR(120) NOT NULL, `city` VARCHAR(120) NOT NULL, `state` VARCHAR(2) NOT NULL, `country_code` VARCHAR(2) NOT NULL DEFAULT 'BR', `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT `fk_branch_addresses_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_branch_addresses_tenant_branch` FOREIGN KEY (`tenant_id`,`branch_id`) REFERENCES `branches` (`tenant_id`,`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_branch_addresses_primary` (`tenant_id`,`branch_id`), KEY `idx_branch_addresses_tenant` (`tenant_id`), CONSTRAINT `chk_branch_addresses_postal_code` CHECK (`postal_code` IS NULL OR LENGTH(`postal_code`) = 8 AND `postal_code` NOT REGEXP '[^0-9]'), CONSTRAINT `chk_branch_addresses_state` CHECK (LENGTH(`state`) = 2 AND `state` NOT REGEXP '[^A-Z]'), CONSTRAINT `chk_branch_addresses_country` CHECK (LENGTH(`country_code`) = 2 AND `country_code` NOT REGEXP '[^A-Z]')) {TableOptions}"""
        ], ["DROP TABLE `branch_addresses`", "DROP TABLE `branches`", "DROP TABLE `companies`", "DROP TABLE `tenants`"]),

        new("202608270004_create_users_memberships.js",
        [
            $"""CREATE TABLE `users` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `name` VARCHAR(160) NOT NULL, `email` VARCHAR(254) NOT NULL, `phone` VARCHAR(20) NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY `uq_users_email` (`email`)) {TableOptions}""",
            $"""CREATE TABLE `tenant_memberships` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `tenant_id` VARCHAR(36) NOT NULL, `user_id` VARCHAR(36) NOT NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'pending', `is_owner` TINYINT(1) NOT NULL DEFAULT 0, `joined_at` DATETIME(6) NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `active_owner_tenant_id` CHAR(36) GENERATED ALWAYS AS (CASE WHEN `is_owner` = 1 AND `status` = 'active' THEN `tenant_id` ELSE NULL END) STORED, CONSTRAINT `fk_memberships_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_memberships_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_memberships_tenant_user` (`tenant_id`,`user_id`), UNIQUE KEY `uq_memberships_one_active_owner` (`active_owner_tenant_id`), KEY `idx_memberships_tenant_status` (`tenant_id`,`status`), KEY `idx_memberships_user_status` (`user_id`,`status`), CONSTRAINT `chk_memberships_status` CHECK (`status` IN ('pending','active','blocked','inactive'))) {TableOptions}"""
        ], ["DROP TABLE `tenant_memberships`", "DROP TABLE `users`"]),

        new("202608270005_create_subscriptions.js",
        [
            $"""CREATE TABLE `subscriptions` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `tenant_id` VARCHAR(36) NOT NULL, `plan_id` VARCHAR(36) NOT NULL, `status` VARCHAR(20) NOT NULL, `starts_at` DATETIME(6) NOT NULL, `trial_ends_at` DATETIME(6) NULL, `ends_at` DATETIME(6) NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `current_tenant_id` CHAR(36) GENERATED ALWAYS AS (CASE WHEN `status` IN ('trialing','active','suspended') THEN `tenant_id` ELSE NULL END) STORED, CONSTRAINT `fk_subscriptions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_subscriptions_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_subscriptions_one_current` (`current_tenant_id`), KEY `idx_subscriptions_tenant_status` (`tenant_id`,`status`), KEY `idx_subscriptions_plan_status` (`plan_id`,`status`), CONSTRAINT `chk_subscriptions_status` CHECK (`status` IN ('trialing','active','suspended','cancelled','expired')), CONSTRAINT `chk_subscriptions_dates` CHECK (`ends_at` IS NULL OR `ends_at` >= `starts_at`)) {TableOptions}"""
        ], ["DROP TABLE `subscriptions`"]),

        new("202608270006_enforce_global_branch_tax_id.js",
        ["ALTER TABLE `branches` DROP INDEX `uq_branches_tenant_tax_id`, ADD UNIQUE KEY `uq_branches_tax_id` (`tax_id`)"],
        ["ALTER TABLE `branches` DROP INDEX `uq_branches_tax_id`, ADD UNIQUE KEY `uq_branches_tenant_tax_id` (`tenant_id`,`tax_id`)"]),

        new("202608270007_create_user_credentials_password_setup_tokens.js",
        [
            $"""CREATE TABLE `user_credentials` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `user_id` VARCHAR(36) NOT NULL, `password_hash` VARCHAR(255) NOT NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT `fk_user_credentials_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, UNIQUE KEY `uq_user_credentials_user` (`user_id`)) {TableOptions}""",
            $"""CREATE TABLE `password_setup_tokens` (`id` VARCHAR(36) NOT NULL PRIMARY KEY, `user_id` VARCHAR(36) NOT NULL, `token_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `purpose` VARCHAR(40) NOT NULL, `expires_at` DATETIME(6) NOT NULL, `used_at` DATETIME(6) NULL, `revoked_at` DATETIME(6) NULL, `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT `fk_password_setup_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, UNIQUE KEY `uq_password_setup_tokens_hash` (`token_hash`), KEY `idx_password_setup_tokens_user_purpose_expiry` (`user_id`,`purpose`,`expires_at`), CONSTRAINT `chk_password_setup_tokens_purpose` CHECK (`purpose` = 'initial_password'), CONSTRAINT `chk_password_setup_tokens_expiry` CHECK (`expires_at` > `created_at`), CONSTRAINT `chk_password_setup_tokens_terminal` CHECK (`used_at` IS NULL OR `revoked_at` IS NULL)) {TableOptions}"""
        ], ["DROP TABLE `password_setup_tokens`", "DROP TABLE `user_credentials`"])
    ];
}
